### ISSUE TITLE
Generic keyboard not responding to arrow keys

### ISSUE THREAD

**Issue by tsiemens** [kierenj/0x10c-DevKit#108] opened 2012-05-05 16:34 UTC
When an arrow key has been pressed, HWI with A = 1 returns 0x0, when it should return 0x80 - 0x83

**Comment by kierenj** [comment] 2012-05-05 17:17
Hi - I do not believe that is the expected behaviour.  "Store next key typed in C register, or 0 if the buffer is empty" - arrow keys are not typed (they are not ASCII printable), they are pressed and released.  I did base the keyboard emulation code on the official emulator - have you experienced something different to DevKit in the official emulator, or do you have any other evidence that arrow keys should be enqueued?

**Comment by Acruid** [comment] 2012-05-05 18:33
http://dcpu.com/highnerd/rc_1/keyboard.txt

The arrow keys should be returning the hex numbers shown in the spec. 0x80 is outside the ascii range of keys so you are right in that they should not be printed. I'm also going to note that the shift key and the control key also return 0x0 in the emulator, when they should be returning 0x90 and 0x91 respectively.

**Comment by tsiemens** [comment] 2012-05-05 18:34
Hi,

No, I suppose not. I was just going through an old program I had  
written in DCPU studio, and the program was based on reading the arrow  
keys from the buffer. I suppose I should be reading them from an  
interrupt now? Is that where the keys are read?

**Comment by kierenj** [comment] 2012-05-05 18:37
Acruid - my interpretation of the spec and the RC1 emulator is that only ASCII-printable keys are queued for reading back with interrupt 1.  Only regular keys and backspace, return, insert and delete are queued up: the others (anything > 0x13, according to the RC1 code) is not queued up.  Unless you can point me at a program running in the official emu returning 0x80 or above from that interrupt call, this is not a bug..

**Comment by Acruid** [comment] 2012-05-06 05:51
After looking into this further, you are correct.  Feel free to close this.

**Closed as completed** 2012-05-06 09:29 UTC
Labels: bug, waitingonfeedback
