### ISSUE TITLE
Moving things around doesn't seem to work

### ISSUE THREAD

**Issue by solbjorg** [kierenj/0x10c-DevKit#20] opened 2012-04-15 18:24 UTC
Moving for example CPU State / Control around crashes DevKit.

**Comment by kierenj** [comment] 2012-04-15 19:09
Thanks for the feedback!  This was something that we chose not to resolve before the release (keen to get people looking at it!) but will be solved in the next release.

**Comment by kierenj** [comment] 2012-04-16 20:47
In fact, I am unable to reproduce this bug (a crash): only that Build Output disappears when the tab is made to float as a popup window.  Can you give some step-by-step instructions?

**Comment by Zibx** [comment] 2012-04-21 09:56
I crashed ide, when I made concat and concated string with itself. and it overwrites the current executed code. It crashed full ide and I lost that function ^_^

**Comment by kierenj** [comment] 2012-04-21 11:16
This sounds like it may not be the same issue as the OP: this relates to dragging windows/panes around in the IDE.  Is it a separate issue?  If so (or either way) could you supply some steps to reproduce he problem please?  

Thanks
Kieren

**Comment by kierenj** [comment] 2012-04-21 14:37
InfiniteFacepalm, I am closing this issue - if you still have the bug, could you give a few example repro steps (to reproduce the error) and I will re-open and investigate - thanks!

**Closed as completed by kierenj** 2012-04-21 14:37 UTC
Labels: bug, waitingonfeedback
